apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-crypto-job
spec:
  schedule: "0 15 * * *"  # 18:00 Israel time = 15:00 UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: fetch-crypto
              image: me-west1-docker.pkg.dev/financesight-463118/crypto/fetch-crypto:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: PYTHONUNBUFFERED
                  value: "1"
              command: ["python"]
              args: ["main.py"]
          restartPolicy: OnFailure
