apiVersion: batch/v1
kind: CronJob
metadata:
  name: aggregator-cronjob
spec:
  schedule: "0 15 * * *"  # Every day at 18:00 Israel time (UTC+3)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: aggregator
              image: gcr.io/financesight-463118/aggregator:v1
              imagePullPolicy: IfNotPresent
              env:
                - name: PYTHONUNBUFFERED
                  value: "1"
              command: ["python"]
              args: ["aggregator_launcher.py"]
          restartPolicy: OnFailure
