apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service_3
  template:
    metadata:
      labels:
        app: service_3
    spec:
      containers:
      - name: service_3
      image: gcr.io.gcr.io/financesight-463118/fetch_news_crypto_service_3:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
      env:
      - name: PYTHONUNBUFFERED
      value: "1"