apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service_1
  template:
    metadata:
      labels:
        app: service_1
    spec:
      containers:
      - name: service_1
      image: gcr.io.gcr.io/financesight-463118/fetch_news_crypto_service_1:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
      env:
      - name: PYTHONUNBUFFERED
      value: "1"