pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }

        stage('Run Integration Tests') {
            steps {
                dir('services/fetch_news_crypto') {
                    script {
                        sh 'docker compose down -v || true'
                        sh 'docker compose up --build --abort-on-container-exit'

                        def exitCode = sh(script: 'docker inspect aggregator --format="{{.State.ExitCode}}"', returnStdout: true).trim()
                        if (exitCode != '0') {
                            error("Aggregator container exited with code ${exitCode}")
                        }
                    }
                }
            }
}

    }

    post {
        always {
            dir('fetch_news_crypto') {
                echo 'Cleaning up containers...'
                sh 'docker compose down -v'
            }
        }
    }
}
