pipeline {
    agent any

    environment {
        COMPOSE_FILE = "docker-compose.yml"
        AGGREGATOR_SERVICE = "aggregator"
    }

    stages {
        stage('Run Tests via Docker Compose') {
            steps {
                dir('services/fetch_news_crypto') {
                    sh '''
                    docker compose -f docker-compose.yml \
                                   up --build --abort-on-container-exit \
                                   --exit-code-from aggregator
                    '''
                }
            }
        }
    }

    post {
        always {
            echo "Cleaning up containers..."
            dir('services/fetch_news_crypto') {
                sh "docker compose -f docker-compose.yml down -v"
            }
        }
    }
}

